#Code converted on 2023-04-28 09:36:31
import os
from pyspark.sql import *
from pyspark.sql.types import *
from pyspark.sql.functions import *
from pyspark import SparkContext
from pyspark.sql.session import SparkSession

def convert_encoding(input_str, from_encoding="ISO-8859-1", to_encoding="UTF-8"):
	return input_str.encode(from_encoding).decode(to_encoding)

udf_convert_encoding = udf(convert_encoding, StringType())

def days_in_year(date_str):
    year = int(date_str[:4])
    if calendar.isleap(year):
        return 366
    else:
        return 365

udf_days_in_year = udf(days_in_year, IntegerType())


# Variable_declaration_comment
os.environ['SOURCE_DIR'] = '/nas_pp/dev/dw/data/conv_253'
SOURCE_DIR = os.getenv('SOURCE_DIR')

os.environ['STG_DIR'] = '/nas_pp/dev/dw/stg'
STG_DIR = os.getenv('STG_DIR')

os.environ['HASH_DIR'] = '/nas_pp/dev/dw/hash'
HASH_DIR = os.getenv('HASH_DIR')

os.environ['FMT_DIR'] = '/nas_pp/dev/dw/fmt'
FMT_DIR = os.getenv('FMT_DIR')

os.environ['BANK_NUM'] = '100'
BANK_NUM = os.getenv('BANK_NUM')

os.environ['DATA_DATE'] = '20140731'
DATA_DATE = os.getenv('DATA_DATE')


# Processing node SBO_LAF_Lkp, type SOURCE
# COLUMN COUNT: 407
# Original node name SboLAFHash, link SBO_LAF_Lkp

SBO_LAF_Lkp = spark.read.csv("SboLAFHash", sep=',', header='false')

# Processing node SBO_ZRF_Lkp, type SOURCE
# COLUMN COUNT: 235
# Original node name SboZRFHash, link SBO_ZRF_Lkp

SBO_ZRF_Lkp = spark.read.csv("SboZRFHash", sep=',', header='false')

# Processing node LkpECF_BANK, type SOURCE
# COLUMN COUNT: 6
# Original node name ECF_BANK_Hash, link LkpECF_BANK

LkpECF_BANK = spark.read.csv("ECF_BANK_Hash", sep=',', header='false')

# Processing node ACCTNH_LKP, type SOURCE
# COLUMN COUNT: 2
# Original node name AcctMortNaturalHash_REF, link ACCTNH_LKP

ACCTNH_LKP = spark.read.csv("AcctMortNaturalHash", sep=',', header='false')

# Processing node SBO_Delq_Lkp, type SOURCE
# COLUMN COUNT: 102
# Original node name SboDelinquencyHash, link SBO_Delq_Lkp

SBO_Delq_Lkp = spark.read.csv("SboDelinquencyHash", sep=',', header='false')

# Processing node SBO_Indx_Lkp, type SOURCE
# COLUMN COUNT: 10
# Original node name SboIndexconHash, link SBO_Indx_Lkp

SBO_Indx_Lkp = spark.read.csv("SboIndexconHash", sep=',', header='false')

# Processing node SBO_NF_LKP, type SOURCE
# COLUMN COUNT: 107
# Original node name SboNewFundingsHash, link SBO_NF_LKP

SBO_NF_LKP = spark.read.csv("SboNewFundingsHash", sep=',', header='false')

# Processing node SBO_Control_Lkp, type SOURCE
# COLUMN COUNT: 63
# Original node name SboControlHash, link SBO_Control_Lkp

SBO_Control_Lkp = spark.read.csv("SboControlHash", sep=',', header='false')

# Processing node SBO_DA_LKP, type SOURCE
# COLUMN COUNT: 64
# Original node name SboDailyAccrualHash, link SBO_DA_LKP

SBO_DA_LKP = spark.read.csv("SboDailyAccrualHash", sep=',', header='false')

# Processing node SRC_IN, type SOURCE
# COLUMN COUNT: 421
# Original node name SBO_LOANMAST_ML_STG, link SRC_IN

SRC_IN = spark.read.csv(""+STG_DIR+"/mort/sbo_loanmast_ml_stg.stg", sep='ý', header='false')

# Processing node SBO_BkrpTrac_LKP, type SOURCE
# COLUMN COUNT: 7
# Original node name SboBkrpTracHash, link SBO_BkrpTrac_LKP

SBO_BkrpTrac_LKP = spark.read.csv("SboBkrpTracHash", sep=',', header='false')

# Processing node SBO_Sale_Lkp, type SOURCE
# COLUMN COUNT: 355
# Original node name SboSaleHash, link SBO_Sale_Lkp

SBO_Sale_Lkp = spark.read.csv("SboSaleHash", sep=',', header='false')

# Processing node SBO_Purchase_LKP, type SOURCE
# COLUMN COUNT: 180
# Original node name SboPurchaseHash, link SBO_Purchase_LKP

SBO_Purchase_LKP = spark.read.csv("SboPurchaseHash", sep=',', header='false')

# Processing node SEQ_IN, type TRANSFORMATION
# COLUMN COUNT: 537
# Original node name XFM_SBO, link SEQ_IN

# Joining dataframes SBO_BkrpTrac_LKP, SBO_Control_Lkp, SBO_DA_LKP, SBO_Delq_Lkp, SBO_Indx_Lkp, SBO_LAF_Lkp, SBO_NF_LKP, SBO_Purchase_LKP, SBO_Sale_Lkp, SBO_ZRF_Lkp, SRC_IN to form SEQ_IN
SEQ_IN_joined = SBO_BkrpTrac_LKP.join(SBO_Control_Lkp, SBO_BkrpTrac_LKP.sys_row_id == SBO_Control_Lkp.sys_row_id, 'inner')
 SBO_Control_Lkp.join(SBO_DA_LKP, SBO_Control_Lkp.sys_row_id == SBO_DA_LKP.sys_row_id, 'inner')
  SBO_DA_LKP.join(SBO_Delq_Lkp, SBO_DA_LKP.sys_row_id == SBO_Delq_Lkp.sys_row_id, 'inner')
   SBO_Delq_Lkp.join(SBO_Indx_Lkp, SBO_Delq_Lkp.sys_row_id == SBO_Indx_Lkp.sys_row_id, 'inner')
    SBO_Indx_Lkp.join(SBO_LAF_Lkp, SBO_Indx_Lkp.sys_row_id == SBO_LAF_Lkp.sys_row_id, 'inner')
     SBO_LAF_Lkp.join(SBO_NF_LKP, SBO_LAF_Lkp.sys_row_id == SBO_NF_LKP.sys_row_id, 'inner')
      SBO_NF_LKP.join(SBO_Purchase_LKP, SBO_NF_LKP.sys_row_id == SBO_Purchase_LKP.sys_row_id, 'inner')
       SBO_Purchase_LKP.join(SBO_Sale_Lkp, SBO_Purchase_LKP.sys_row_id == SBO_Sale_Lkp.sys_row_id, 'inner')
        SBO_Sale_Lkp.join(SBO_ZRF_Lkp, SBO_Sale_Lkp.sys_row_id == SBO_ZRF_Lkp.sys_row_id, 'inner')
         SBO_ZRF_Lkp.join(SRC_IN, SBO_ZRF_Lkp.sys_row_id == SRC_IN.sys_row_id, 'inner')
SEQ_IN = SEQ_IN_joined
SEQ_IN = SEQ_IN.withColumn("MFPB", (when(((length(trim(SBO_ZRF_Lkp.PRINCIPAL_BALANCE)) > lit(0)) &(TRY_trim(SBO_ZRF_Lkp.PRINCIPAL_BALANCE).cast(NUMERIC) IS NOT None) ),(trim(SBO_ZRF_Lkp.PRINCIPAL_BALANCE) )).otherwise(lit(0))))
	
SEQ_IN = SEQ_IN.withColumn("MSPB", (when(((length(trim(SBO_ZRF_Lkp.SECOND_PRINCIPAL_BALANCE)) > lit(0)) &(TRY_trim(SBO_ZRF_Lkp.SECOND_PRINCIPAL_BALANCE).cast(NUMERIC) IS NOT None) ),(trim(SBO_ZRF_Lkp.SECOND_PRINCIPAL_BALANCE) )).otherwise(lit(0))))
	
SEQ_IN = SEQ_IN.withColumn("MFPBPlusMSPB", MFPB + MSPB).select(
	SRC_IN.CALC_MTG_BANK.alias('CALC_MTG_BANK'),
	SRC_IN.MTG_BANK.alias('MTG_BANK'),
	SRC_IN.MTG_LOAN_NO.alias('MTG_LOAN_NO'),
	SRC_IN.ADDITIONAL_ALL_AMORTIZATION.alias('ADDITIONAL_ALL_AMORTIZATION'),
	SRC_IN.ADDITIONAL_GAAP_AMORTIZATION.alias('ADDITIONAL_GAAP_AMORTIZATION'),
	SRC_IN.ADDITIONAL_INTEREST_INDICATOR.alias('ADDITIONAL_INTEREST_INDICATOR'),
	SRC_IN.ADDITIONAL_TAX_AMORTIZATION.alias('ADDITIONAL_TAX_AMORTIZATION'),
	SRC_IN.ADJ_PRIOR_PERIOD_INTEREST_DUE.alias('ADJ_PRIOR_PERIOD_INTEREST_DUE'),
	SRC_IN.ACCRUED_FEES.alias('ACCRUED_FEES'),
	SRC_IN.ACTUAL_ACTUAL_OVERRIDE.alias('ACTUAL_ACTUAL_OVERRIDE'),
	SRC_IN.ADJ_GROSS_INTEREST_RECEIVED.alias('ADJ_GROSS_INTEREST_RECEIVED'),
	SRC_IN.ADJ_GROSS_PRINCIPAL_RECEIVED.alias('ADJ_GROSS_PRINCIPAL_RECEIVED'),
	SRC_IN.ADJ_INTEREST_CHARGED_AMOUNT.alias('ADJ_INTEREST_CHARGED_AMOUNT'),
	SRC_IN.ADJ_PART_INTEREST_RECEIVED.alias('ADJ_PART_INTEREST_RECEIVED'),
	SRC_IN.ADJ_PART_PRINCIPAL_RECEIVED.alias('ADJ_PART_PRINCIPAL_RECEIVED'),
	SRC_IN.ADJ_PART_SERV_FEE_EARNED.alias('ADJ_PART_SERV_FEE_EARNED'),
	SRC_IN.ADJ_PART_SERV_FEE_PAID.alias('ADJ_PART_SERV_FEE_PAID'),
	SRC_IN.ADJ_LOANHIST_TRAN_TYPE.alias('ADJ_LOANHIST_TRAN_TYPE'),
	SRC_IN.APPRAISAL_DATE.alias('APPRAISAL_DATE'),
	SRC_IN.APPRAISED_VALUE.alias('APPRAISED_VALUE'),
	SRC_IN.ARREARAGE_BALANCE.alias('ARREARAGE_BALANCE'),
	SRC_IN.ASSIGNED_CUSTNO.alias('ASSIGNED_CUSTNO'),
	SRC_IN.ASSIGNMENT_HOLDER_CODE.alias('ASSIGNMENT_HOLDER_CODE'),
	SRC_IN.ASSUMPTION_STATUS.alias('ASSUMPTION_STATUS'),
	SRC_IN.ATTORNEY_REFERRAL_DATE.alias('ATTORNEY_REFERRAL_DATE'),
	SRC_IN.AUDIT_CODE.alias('AUDIT_CODE'),
	SRC_IN.BANKRUPTCY_STATUS.alias('BANKRUPTCY_STATUS'),
	SRC_IN.BANKRUPTCY_STATUS_DATE.alias('BANKRUPTCY_STATUS_DATE'),
	SRC_IN.BORROWER_FIRST_NAME.alias('BORROWER_FIRST_NAME'),
	SRC_IN.BORROWER_NAME.alias('BORROWER_NAME'),
	SRC_IN.BORROWER_SSN_NUMBER.alias('BORROWER_SSN_NUMBER'),
	SRC_IN.CMR_APPRAISED_VALUE.alias('CMR_APPRAISED_VALUE'),
	SRC_IN.CMR_INSURANCE_CODE.alias('CMR_INSURANCE_CODE'),
	SRC_IN.CMR_LIEN_CODE.alias('CMR_LIEN_CODE'),
	SRC_IN.CMR_LOAN_TERM.alias('CMR_LOAN_TERM'),
	SRC_IN.CMR_PROPERTY_TYPE.alias('CMR_PROPERTY_TYPE'),
	SRC_IN.CMR_SECURITY.alias('CMR_SECURITY'),
	SRC_IN.CMR_SENIOR_LIEN_BALANCE.alias('CMR_SENIOR_LIEN_BALANCE'),
	SRC_IN.CMR_TEASE_PERIOD_END_DATE.alias('CMR_TEASE_PERIOD_END_DATE'),
	SRC_IN.COBORROWER_FIRST_NAME.alias('COBORROWER_FIRST_NAME'),
	SRC_IN.COBORROWER_NAME.alias('COBORROWER_NAME'),
	SRC_IN.COBORROWER_SSN_NUMBER.alias('COBORROWER_SSN_NUMBER'),
	SRC_IN.COMMITMENT_NUMBER.alias('COMMITMENT_NUMBER'),
	SRC_IN.COMMITMENT_NUMBER_INV.alias('COMMITMENT_NUMBER_INV'),
	SRC_IN.COMMITMENT_TYPE.alias('COMMITMENT_TYPE'),
	SRC_IN.CONDOMINIUM_PROJECT.alias('CONDOMINIUM_PROJECT'),
	SRC_IN.CORPORATE_ADVANCE_BALANCE.alias('CORPORATE_ADVANCE_BALANCE'),
	SRC_IN.COUNTRY_CODE.alias('COUNTRY_CODE'),
	SRC_IN.COUNTY_CODE.alias('COUNTY_CODE'),
	SRC_IN.CURRENCY_CODE.alias('CURRENCY_CODE'),
	SRC_IN.CYCLES_CHARGED_SPECIAL_FEE.alias('CYCLES_CHARGED_SPECIAL_FEE'),
	SRC_IN.CYCLES_WITH_WARNINGS.alias('CYCLES_WITH_WARNINGS'),
	SRC_IN.DATE_ARCHIVED.alias('DATE_ARCHIVED'),
	SRC_IN.DEED_HOLDER_CODE.alias('DEED_HOLDER_CODE'),
	SRC_IN.DEFAULT_STATUS.alias('DEFAULT_STATUS'),
	SRC_IN.DEFERRED_INTEREST.alias('DEFERRED_INTEREST'),
	SRC_IN.DEFERRED_MAX_PRINCIPAL.alias('DEFERRED_MAX_PRINCIPAL'),
	SRC_IN.DEFERRED_PRIN_LAST_INV_CYCLE.alias('DEFERRED_PRIN_LAST_INV_CYCLE'),
	SRC_IN.DEFERRED_PRINCIPAL.alias('DEFERRED_PRINCIPAL'),
	SRC_IN.DOCUMENTS_MAILED_BY.alias('DOCUMENTS_MAILED_BY'),
	SRC_IN.DOCUMENTS_MAILING_DATE.alias('DOCUMENTS_MAILING_DATE'),
	SRC_IN.DOCUMENTS_REQUESTED_BY.alias('DOCUMENTS_REQUESTED_BY'),
	SRC_IN.DOCUMENTS_REQUESTED_DATE.alias('DOCUMENTS_REQUESTED_DATE'),
	SRC_IN.DOCUMENTS_RETURNED_BY.alias('DOCUMENTS_RETURNED_BY'),
	SRC_IN.DOCUMENTS_RETURNED_DATE.alias('DOCUMENTS_RETURNED_DATE'),
	SRC_IN.DSI_DAYS_IN_YEAR_CALC_CODE.alias('DSI_DAYS_IN_YEAR_CALC_CODE'),
	SRC_IN.DSI_INDICATOR_CODE.alias('DSI_INDICATOR_CODE'),
	SRC_IN.DSI_CAP_INTEREST_CODE.alias('DSI_CAP_INTEREST_CODE'),
	SRC_IN.DSI_INTEREST_ROUNDING_CODE.alias('DSI_INTEREST_ROUNDING_CODE'),
	SRC_IN.DUE_DATE_DAY_OF_MONTH.alias('DUE_DATE_DAY_OF_MONTH'),
	SRC_IN.EARLIEST_ALLOWED_DUE_DATE.alias('EARLIEST_ALLOWED_DUE_DATE'),
	SRC_IN.ENVIRONMENTAL_CODE.alias('ENVIRONMENTAL_CODE'),
	SRC_IN.ENVIRONMENTAL_CODE_DATE.alias('ENVIRONMENTAL_CODE_DATE'),
	SRC_IN.ESCROW_ADVANCE_BALANCE.alias('ESCROW_ADVANCE_BALANCE'),
	SRC_IN.ESCROW_ADVANCE_RECOVERED.alias('ESCROW_ADVANCE_RECOVERED'),
	SRC_IN.ESCROW_BALANCE.alias('ESCROW_BALANCE'),
	SRC_IN.FAMILY_ROLE.alias('FAMILY_ROLE'),
	SRC_IN.FIRST_PAYMENT_DATE.alias('FIRST_PAYMENT_DATE'),
	SRC_IN.FIRST_PAYMENT_INTEREST_ADJ.alias('FIRST_PAYMENT_INTEREST_ADJ'),
	SRC_IN.FNMA_ACTION_CODE.alias('FNMA_ACTION_CODE'),
	SRC_IN.FNMA_ACTION_DATE.alias('FNMA_ACTION_DATE'),
	SRC_IN.FNMA_DELINQUENT_REASON_CODE.alias('FNMA_DELINQUENT_REASON_CODE'),
	SRC_IN.FNMA_DELINQUENT_STATUS_CODE.alias('FNMA_DELINQUENT_STATUS_CODE'),
	SRC_IN.FNMA_DELINQUENT_STATUS_DATE.alias('FNMA_DELINQUENT_STATUS_DATE'),
	SRC_IN.FNMA_STATUS_CODE.alias('FNMA_STATUS_CODE'),
	SRC_IN.FOLLOW_UP_ACTION_CODE.alias('FOLLOW_UP_ACTION_CODE'),
	SRC_IN.FOLLOW_UP_DATE.alias('FOLLOW_UP_DATE'),
	SRC_IN.FOLLOW_UP_PERSON.alias('FOLLOW_UP_PERSON'),
	SRC_IN.FORECAST_ACCRUED_INTEREST.alias('FORECAST_ACCRUED_INTEREST'),
	SRC_IN.FORECLOSURE_STATUS.alias('FORECLOSURE_STATUS'),
	SRC_IN.FORECLOSURE_STATUS_DATE.alias('FORECLOSURE_STATUS_DATE'),
	SRC_IN.FREDDIE_MAC_PROCESSING_STATUS.alias('FREDDIE_MAC_PROCESSING_STATUS'),
	SRC_IN.HMP_INCENTIVE_END_DATE.alias('HMP_INCENTIVE_END_DATE'),
	SRC_IN.INDEMNIFICATION_STATUS.alias('INDEMNIFICATION_STATUS'),
	SRC_IN.INITIAL_INV_SF_RATE.alias('INITIAL_INV_SF_RATE'),
	SRC_IN.INITIAL_REPORT_RECEIVED_DATE.alias('INITIAL_REPORT_RECEIVED_DATE'),
	SRC_IN.INTEREST_CALCULATION_CODE.alias('INTEREST_CALCULATION_CODE'),
	SRC_IN.INTEREST_CHARGED_TO_DATE.alias('INTEREST_CHARGED_TO_DATE'),
	SRC_IN.INTEREST_METHOD_CODE.alias('INTEREST_METHOD_CODE'),
	SRC_IN.INTEREST_NOT_IN_INV_CUSTODIAL.alias('INTEREST_NOT_IN_INV_CUSTODIAL'),
	SRC_IN.INTEREST_ON_ARREARS_BALANCE.alias('INTEREST_ON_ARREARS_BALANCE'),
	SRC_IN.INTEREST_ONLY_FLAG.alias('INTEREST_ONLY_FLAG'),
	SRC_IN.INTEREST_PAID_TO_DATE.alias('INTEREST_PAID_TO_DATE'),
	SRC_IN.INTEREST_STRIP_INDICATOR.alias('INTEREST_STRIP_INDICATOR'),
	SRC_IN.INTERIM_PAYOFF_REVERSED_IND.alias('INTERIM_PAYOFF_REVERSED_IND'),
	SRC_IN.INVESTOR_CUSTNO.alias('INVESTOR_CUSTNO'),
	SRC_IN.INVESTOR_INTEREST_DUE.alias('INVESTOR_INTEREST_DUE'),
	SRC_IN.INVESTOR_LOAN_NUMBER.alias('INVESTOR_LOAN_NUMBER'),
	SRC_IN.INVESTOR_MARKETED_IND.alias('INVESTOR_MARKETED_IND'),
	SRC_IN.LAST_COLLECT_HIST_SEQ_NUM.alias('LAST_COLLECT_HIST_SEQ_NUM'),
	SRC_IN.LAST_DAILY_HIST_SEQ_NUM.alias('LAST_DAILY_HIST_SEQ_NUM'),
	SRC_IN.LAST_INV_HIST_SEQUENCE_NUMBER.alias('LAST_INV_HIST_SEQUENCE_NUMBER'),
	SRC_IN.LAST_INV_CUTOFF_HIST_SEQ_NUM.alias('LAST_INV_CUTOFF_HIST_SEQ_NUM'),
	SRC_IN.LAST_LOANHIST_SEQUENCE_NUMBER.alias('LAST_LOANHIST_SEQUENCE_NUMBER'),
	SRC_IN.LAST_MODIFICATION_DATE.alias('LAST_MODIFICATION_DATE'),
	SRC_IN.LAST_OUTBOUND_SEQ_NUM.alias('LAST_OUTBOUND_SEQ_NUM'),
	SRC_IN.LAST_PART_GUARANTY_FEE_ADV.alias('LAST_PART_GUARANTY_FEE_ADV'),
	SRC_IN.LAST_PART_NOTE_INT_ADV.alias('LAST_PART_NOTE_INT_ADV'),
	SRC_IN.LAST_PART_PRIN_ADV.alias('LAST_PART_PRIN_ADV'),
	SRC_IN.LAST_PART_SERV_FEE_ADV.alias('LAST_PART_SERV_FEE_ADV'),
	SRC_IN.LAST_PAYMENT_RECEIVED_DATE.alias('LAST_PAYMENT_RECEIVED_DATE'),
	SRC_IN.LAST_PROPAGATE_SEQUENCE_NUMBER.alias('LAST_PROPAGATE_SEQUENCE_NUMBER'),
	SRC_IN.LAST_SCHED_NOTE_RATE.alias('LAST_SCHED_NOTE_RATE'),
	SRC_IN.LAST_SCHED_PMT_AMT.alias('LAST_SCHED_PMT_AMT'),
	SRC_IN.LAST_SCHED_PUR_SERV_FEE_RATE.alias('LAST_SCHED_PUR_SERV_FEE_RATE'),
	SRC_IN.LAST_SERV_HIST_SEQUENCE_NUMBER.alias('LAST_SERV_HIST_SEQUENCE_NUMBER'),
	SRC_IN.LAST_STATUS_CHANGE_SEQ_NUMBER.alias('LAST_STATUS_CHANGE_SEQ_NUMBER'),
	SRC_IN.LAST_VALID_ARM_DUE_DATE.alias('LAST_VALID_ARM_DUE_DATE'),
	SRC_IN.LAST_VALID_OUTBOUND_SEQ_NUM.alias('LAST_VALID_OUTBOUND_SEQ_NUM'),
	SRC_IN.LAST_VALID_OUTBOUND_GAP.alias('LAST_VALID_OUTBOUND_GAP'),
	SRC_IN.LEGAL_LITIGATION_CODE.alias('LEGAL_LITIGATION_CODE'),
	SRC_IN.LIEN_TYPE.alias('LIEN_TYPE'),
	SRC_IN.LINE_OF_CREDIT_INDICATOR.alias('LINE_OF_CREDIT_INDICATOR'),
	SRC_IN.LINKED_LOAN_NUMBER.alias('LINKED_LOAN_NUMBER'),
	SRC_IN.LIQUIDATION_TYPE.alias('LIQUIDATION_TYPE'),
	SRC_IN.LOAN_DATE_TO_START_AMORT_PREM.alias('LOAN_DATE_TO_START_AMORT_PREM'),
	SRC_IN.LOAN_DISCOUNT_BALANCE.alias('LOAN_DISCOUNT_BALANCE'),
	SRC_IN.LOAN_DUE_DATE.alias('LOAN_DUE_DATE'),
	SRC_IN.LOAN_EFFECTIVE_YIELD.alias('LOAN_EFFECTIVE_YIELD'),
	SRC_IN.LOAN_LAST_PURCHASE_CUTOFF_DATE.alias('LOAN_LAST_PURCHASE_CUTOFF_DATE'),
	SRC_IN.LOAN_NEG_AM_BALANCE.alias('LOAN_NEG_AM_BALANCE'),
	SRC_IN.LOAN_NOTE_RATE.alias('LOAN_NOTE_RATE'),
	SRC_IN.LOAN_NUM_MONTHS_TO_ACCRUE.alias('LOAN_NUM_MONTHS_TO_ACCRUE'),
	SRC_IN.LOAN_NUMERIC.alias('LOAN_NUMERIC'),
	SRC_IN.LOAN_PARTICIPANT_PERCENT.alias('LOAN_PARTICIPANT_PERCENT'),
	SRC_IN.LOAN_PARTICIPANT_PRINCIPAL.alias('LOAN_PARTICIPANT_PRINCIPAL'),
	SRC_IN.LOAN_PAYMENT_AMOUNT.alias('LOAN_PAYMENT_AMOUNT'),
	SRC_IN.LOAN_PREMIUM_BALANCE.alias('LOAN_PREMIUM_BALANCE'),
	SRC_IN.LOAN_PREPAYMENT_PENALTY_CODE.alias('LOAN_PREPAYMENT_PENALTY_CODE'),
	SRC_IN.LOAN_PREPAY_PEN_EXP_DATE.alias('LOAN_PREPAY_PEN_EXP_DATE'),
	SRC_IN.LOAN_PRINCIPAL.alias('LOAN_PRINCIPAL'),
	SRC_IN.LOAN_REMAINING_TERM.alias('LOAN_REMAINING_TERM'),
	SRC_IN.LOAN_STATUS.alias('LOAN_STATUS'),
	SRC_IN.LOAN_STATUS_DATE.alias('LOAN_STATUS_DATE'),
	SRC_IN.LOAN_TYPE.alias('LOAN_TYPE'),
	SRC_IN.MASTER_SERV_CUSTNO.alias('MASTER_SERV_CUSTNO'),
	SRC_IN.MASTER_SERV_FIN_INST_CUSTNO.alias('MASTER_SERV_FIN_INST_CUSTNO'),
	SRC_IN.MATURITY_DATE.alias('MATURITY_DATE'),
	SRC_IN.MAXIMUM_INVESTOR_BALANCE.alias('MAXIMUM_INVESTOR_BALANCE'),
	SRC_IN.MI_CARRIER_CUSTNO.alias('MI_CARRIER_CUSTNO'),
	SRC_IN.MI_CERTIFICATE_HOLDER_CODE.alias('MI_CERTIFICATE_HOLDER_CODE'),
	SRC_IN.MI_CERTIFICATE_NUMBER.alias('MI_CERTIFICATE_NUMBER'),
	SRC_IN.MI_COVERAGE_AMOUNT.alias('MI_COVERAGE_AMOUNT'),
	SRC_IN.MI_COVERAGE_CODE.alias('MI_COVERAGE_CODE'),
	SRC_IN.MI_MASTER_CERTIFICATE_NUMBER.alias('MI_MASTER_CERTIFICATE_NUMBER'),
	SRC_IN.MI_MASTER_COVERAGE_AMOUNT.alias('MI_MASTER_COVERAGE_AMOUNT'),
	SRC_IN.MI_MASTER_COVERAGE_CODE.alias('MI_MASTER_COVERAGE_CODE'),
	SRC_IN.MI_MAST_CARRIER_CUSTNO.alias('MI_MAST_CARRIER_CUSTNO'),
	SRC_IN.MINIMUM_CUSTODIAL_ACCOUNT_BAL.alias('MINIMUM_CUSTODIAL_ACCOUNT_BAL'),
	SRC_IN.MODIFICATION_REASON_CODE.alias('MODIFICATION_REASON_CODE'),
	SRC_IN.NEGATIVE_AMORTIZATION_BALANCE.alias('NEGATIVE_AMORTIZATION_BALANCE'),
	SRC_IN.NEXT_CYCLE_INTEREST.alias('NEXT_CYCLE_INTEREST'),
	SRC_IN.NOTE_HOLDER_CODE.alias('NOTE_HOLDER_CODE'),
	SRC_IN.NOTICE_OF_DEFAULT_FILED_DATE.alias('NOTICE_OF_DEFAULT_FILED_DATE'),
	SRC_IN.NUMBER_OF_TIMES_CALCULATED.alias('NUMBER_OF_TIMES_CALCULATED'),
	SRC_IN.NUMBER_OF_UNITS.alias('NUMBER_OF_UNITS'),
	SRC_IN.ONGOING_INV_SF_EFFECTIVE_DATE.alias('ONGOING_INV_SF_EFFECTIVE_DATE'),
	SRC_IN.ONGOING_INV_SF_RATE.alias('ONGOING_INV_SF_RATE'),
	SRC_IN.OPTION_ARM_EXPIRATION_DATE.alias('OPTION_ARM_EXPIRATION_DATE'),
	SRC_IN.OPTION_ARM_INDICATOR.alias('OPTION_ARM_INDICATOR'),
	SRC_IN.OPTION_ARM_INTEREST_ONLY_IND.alias('OPTION_ARM_INTEREST_ONLY_IND'),
	SRC_IN.ORIG_INTER_COMPANY_VALUATION.alias('ORIG_INTER_COMPANY_VALUATION'),
	SRC_IN.ORIGINAL_BORROWER_FIRST_NAME.alias('ORIGINAL_BORROWER_FIRST_NAME'),
	SRC_IN.ORIGINAL_BORROWER_NAME.alias('ORIGINAL_BORROWER_NAME'),
	SRC_IN.ORIGINAL_COBORROWER_FIRST_NAME.alias('ORIGINAL_COBORROWER_FIRST_NAME'),
	SRC_IN.ORIGINAL_COBORROWER_NAME.alias('ORIGINAL_COBORROWER_NAME'),
	SRC_IN.ORIGINAL_LOAN_BALANCE.alias('ORIGINAL_LOAN_BALANCE'),
	SRC_IN.ORIGINAL_PAYMENT_AMOUNT.alias('ORIGINAL_PAYMENT_AMOUNT'),
	SRC_IN.ORIGINAL_RATE.alias('ORIGINAL_RATE'),
	SRC_IN.ORIGINAL_SALES_PRICE.alias('ORIGINAL_SALES_PRICE'),
	SRC_IN.ORIGINAL_TERM.alias('ORIGINAL_TERM'),
	SRC_IN.ORIGINATION_DATE.alias('ORIGINATION_DATE'),
	SRC_IN.OTHER_LOAN_NUMERIC.alias('OTHER_LOAN_NUMERIC'),
	SRC_IN.OWNER_OCCUPANCY_CODE.alias('OWNER_OCCUPANCY_CODE'),
	SRC_IN.PAYMENT_HOLD_FLAG.alias('PAYMENT_HOLD_FLAG'),
	SRC_IN.PAYMENTS_PER_YEAR.alias('PAYMENTS_PER_YEAR'),
	SRC_IN.PAYOFF_EFFECTIVE_DATE.alias('PAYOFF_EFFECTIVE_DATE'),
	SRC_IN.PAYOFF_INTEREST_REMITTED.alias('PAYOFF_INTEREST_REMITTED'),
	SRC_IN.PAYOFF_PAYMENT_HOLD_FLAG.alias('PAYOFF_PAYMENT_HOLD_FLAG'),
	SRC_IN.PAYOFF_POSTING_INDICATOR.alias('PAYOFF_POSTING_INDICATOR'),
	SRC_IN.PAYOFF_PRINCIPAL_REMITTED.alias('PAYOFF_PRINCIPAL_REMITTED'),
	SRC_IN.PAYOFF_STATUS.alias('PAYOFF_STATUS'),
	SRC_IN.PAYOFF_TRACKING_CODE.alias('PAYOFF_TRACKING_CODE'),
	SRC_IN.PAYOFF_TRACKING_DATE.alias('PAYOFF_TRACKING_DATE'),
	SRC_IN.PENDING_COMMITMENT_NUMBER.alias('PENDING_COMMITMENT_NUMBER'),
	SRC_IN.PMT_CALCULATION_CODE.alias('PMT_CALCULATION_CODE'),
	SRC_IN.PMT_CHANGE_FREQUENCY.alias('PMT_CHANGE_FREQUENCY'),
	SRC_IN.PMT_DECREASE_MAXIMUM.alias('PMT_DECREASE_MAXIMUM'),
	SRC_IN.PMT_FIRST_CHANGE.alias('PMT_FIRST_CHANGE'),
	SRC_IN.PMT_FIRST_CHANGE_FREQUENCY.alias('PMT_FIRST_CHANGE_FREQUENCY'),
	SRC_IN.PMT_FIRST_DISCOUNT_EXPIRE_DATE.alias('PMT_FIRST_DISCOUNT_EXPIRE_DATE'),
	SRC_IN.PMT_FIRST_DISCOUNT_PERCENT.alias('PMT_FIRST_DISCOUNT_PERCENT'),
	SRC_IN.PMT_FULL_ADJUSTMENT_FREQUENCY.alias('PMT_FULL_ADJUSTMENT_FREQUENCY'),
	SRC_IN.PMT_INCREASE_MAXIMUM.alias('PMT_INCREASE_MAXIMUM'),
	SRC_IN.PMT_LAST_CHANGE.alias('PMT_LAST_CHANGE'),
	SRC_IN.PMT_MAX_LOAN_AMOUNT.alias('PMT_MAX_LOAN_AMOUNT'),
	SRC_IN.PMT_NEXT_CHANGE.alias('PMT_NEXT_CHANGE'),
	SRC_IN.PMT_NEXT_FULL_ADJUSTMENT_DATE.alias('PMT_NEXT_FULL_ADJUSTMENT_DATE'),
	SRC_IN.PMT_OPTIONAL_INCREASE_MAXIMUM.alias('PMT_OPTIONAL_INCREASE_MAXIMUM'),
	SRC_IN.PMT_OPTIONAL_DECREASE_MAXIMUM.alias('PMT_OPTIONAL_DECREASE_MAXIMUM'),
	SRC_IN.POST_FORECLOSURE_STATUS.alias('POST_FORECLOSURE_STATUS'),
	SRC_IN.POST_FORECLOSURE_STATUS_DATE.alias('POST_FORECLOSURE_STATUS_DATE'),
	SRC_IN.PREV_NET_AMORTIZED_INT_REC.alias('PREV_NET_AMORTIZED_INT_REC'),
	SRC_IN.PREV_NET_AMORTIZED_INT_RESERVE.alias('PREV_NET_AMORTIZED_INT_RESERVE'),
	SRC_IN.PREV_NET_AMORTIZED_SERVICE_FEE.alias('PREV_NET_AMORTIZED_SERVICE_FEE'),
	SRC_IN.PREPAYMENT_PENALTY_WAIVED_CODE.alias('PREPAYMENT_PENALTY_WAIVED_CODE'),
	SRC_IN.PREVIOUS_INV_SOLD_DUE_DATE.alias('PREVIOUS_INV_SOLD_DUE_DATE'),
	SRC_IN.PREVIOUS_INVESTOR_CUSTNO.alias('PREVIOUS_INVESTOR_CUSTNO'),
	SRC_IN.PREVIOUS_INVESTOR_SOLD_BALANCE.alias('PREVIOUS_INVESTOR_SOLD_BALANCE'),
	SRC_IN.PREVIOUS_SALE_NUMBER.alias('PREVIOUS_SALE_NUMBER'),
	SRC_IN.PRINCIPAL_NOT_IN_INV_CUSTODIAL.alias('PRINCIPAL_NOT_IN_INV_CUSTODIAL'),
	SRC_IN.PRINCIPAL_ON_ARREARS_BALANCE.alias('PRINCIPAL_ON_ARREARS_BALANCE'),
	SRC_IN.PRIOR_SCHEDULED_BALANCE.alias('PRIOR_SCHEDULED_BALANCE'),
	SRC_IN.PROPERTY_CITY.alias('PROPERTY_CITY'),
	SRC_IN.PROPERTY_STREET_DIRECTION.alias('PROPERTY_STREET_DIRECTION'),
	SRC_IN.PROPERTY_STREET_NAME.alias('PROPERTY_STREET_NAME'),
	SRC_IN.PROPERTY_STREET_NUMBER.alias('PROPERTY_STREET_NUMBER'),
	SRC_IN.PROPERTY_TYPE.alias('PROPERTY_TYPE'),
	SRC_IN.PROPERTY_USE_CODE.alias('PROPERTY_USE_CODE'),
	SRC_IN.PURCHASE_NUMBER.alias('PURCHASE_NUMBER'),
	SRC_IN.PURPOSE_CODE.alias('PURPOSE_CODE'),
	SRC_IN.PUR_CURRENT_SERVICE_FEE_RATE.alias('PUR_CURRENT_SERVICE_FEE_RATE'),
	SRC_IN.PUR_CYCLE_FIXED_SERV_FEE_AMT.alias('PUR_CYCLE_FIXED_SERV_FEE_AMT'),
	SRC_IN.PUR_CYCLE_FIXED_SERV_FEE_BP.alias('PUR_CYCLE_FIXED_SERV_FEE_BP'),
	SRC_IN.PUR_CYCLE_FIXED_SERV_FEE_CODE.alias('PUR_CYCLE_FIXED_SERV_FEE_CODE'),
	SRC_IN.PUR_NET_YIELD_ADDL_YIELD.alias('PUR_NET_YIELD_ADDL_YIELD'),
	SRC_IN.PUR_NET_YIELD_FIRST_MAX_DECR.alias('PUR_NET_YIELD_FIRST_MAX_DECR'),
	SRC_IN.PUR_NET_YIELD_FIRST_MAX_INCR.alias('PUR_NET_YIELD_FIRST_MAX_INCR'),
	SRC_IN.PUR_NET_YIELD_LIFE_CAP.alias('PUR_NET_YIELD_LIFE_CAP'),
	SRC_IN.PUR_NET_YIELD_LIFE_FLOOR.alias('PUR_NET_YIELD_LIFE_FLOOR'),
	SRC_IN.PUR_NET_YIELD_MARGIN.alias('PUR_NET_YIELD_MARGIN'),
	SRC_IN.PUR_NET_YIELD_MAX_RATE_DECR.alias('PUR_NET_YIELD_MAX_RATE_DECR'),
	SRC_IN.PUR_NET_YIELD_MAX_RATE_INCR.alias('PUR_NET_YIELD_MAX_RATE_INCR'),
	SRC_IN.PUR_NET_YIELD_MAX_SERV_FEE.alias('PUR_NET_YIELD_MAX_SERV_FEE'),
	SRC_IN.PUR_NET_YIELD_MIN_SERV_FEE.alias('PUR_NET_YIELD_MIN_SERV_FEE'),
	SRC_IN.PUR_NET_YIELD_ROUNDING_CODE.alias('PUR_NET_YIELD_ROUNDING_CODE'),
	SRC_IN.PUR_NET_YIELD_ROUNDING_FACTOR.alias('PUR_NET_YIELD_ROUNDING_FACTOR'),
	SRC_IN.PUR_PMT_FIXED_SERV_FEE_AMT.alias('PUR_PMT_FIXED_SERV_FEE_AMT'),
	SRC_IN.PUR_SERV_FEE_CALC_CODE.alias('PUR_SERV_FEE_CALC_CODE'),
	SRC_IN.PUR_SERV_FEE_PRIORITY_CODE.alias('PUR_SERV_FEE_PRIORITY_CODE'),
	SRC_IN.RATE_BASE_INDEX_VALUE.alias('RATE_BASE_INDEX_VALUE'),
	SRC_IN.RATE_CHANGE_FREQUENCY.alias('RATE_CHANGE_FREQUENCY'),
	SRC_IN.RATE_DAYS_BEFORE_PMT_CHANGE.alias('RATE_DAYS_BEFORE_PMT_CHANGE'),
	SRC_IN.RATE_EFFECTIVE_DATE.alias('RATE_EFFECTIVE_DATE'),
	SRC_IN.RATE_FIRST_CHANGE.alias('RATE_FIRST_CHANGE'),
	SRC_IN.RATE_FIRST_MAX_DECREASE.alias('RATE_FIRST_MAX_DECREASE'),
	SRC_IN.RATE_FIRST_MAX_INCREASE.alias('RATE_FIRST_MAX_INCREASE'),
	SRC_IN.RATE_INDEX_CODE.alias('RATE_INDEX_CODE'),
	SRC_IN.RATE_INDEX_DAYS_BEFORE_CHANGE.alias('RATE_INDEX_DAYS_BEFORE_CHANGE'),
	SRC_IN.RATE_INDEX_ROUNDING_CODE.alias('RATE_INDEX_ROUNDING_CODE'),
	SRC_IN.RATE_LAST_CHANGE.alias('RATE_LAST_CHANGE'),
	SRC_IN.RATE_LIFE_CAP.alias('RATE_LIFE_CAP'),
	SRC_IN.RATE_LIFE_MINIMUM.alias('RATE_LIFE_MINIMUM'),
	SRC_IN.RATE_MARGIN.alias('RATE_MARGIN'),
	SRC_IN.RATE_MAX_DECREASE.alias('RATE_MAX_DECREASE'),
	SRC_IN.RATE_MAX_INCREASE.alias('RATE_MAX_INCREASE'),
	SRC_IN.RATE_MINIMUM_INDEX_CHANGE.alias('RATE_MINIMUM_INDEX_CHANGE'),
	SRC_IN.RATE_NEXT_CHANGE.alias('RATE_NEXT_CHANGE'),
	SRC_IN.RATE_ROUNDING_CODE.alias('RATE_ROUNDING_CODE'),
	SRC_IN.RATE_ROUNDING_FACTOR.alias('RATE_ROUNDING_FACTOR'),
	SRC_IN.RE_PERFORMING_INDICATOR.alias('RE_PERFORMING_INDICATOR'),
	SRC_IN.RECOURSE_CODE.alias('RECOURSE_CODE'),
	SRC_IN.RECOVER_ESCROW_ADVANCE_IND.alias('RECOVER_ESCROW_ADVANCE_IND'),
	SRC_IN.REG_AB_ACCRUED_FEES.alias('REG_AB_ACCRUED_FEES'),
	SRC_IN.REG_AB_LAST_HIST_SEQ_NUMBER.alias('REG_AB_LAST_HIST_SEQ_NUMBER'),
	SRC_IN.REG_AB_SALE_NET_INT_ADV.alias('REG_AB_SALE_NET_INT_ADV'),
	SRC_IN.REG_AB_SALE_PRINCIPAL_ADV.alias('REG_AB_SALE_PRINCIPAL_ADV'),
	SRC_IN.REG_AB_SALE_SOLD_PRINCIPAL.alias('REG_AB_SALE_SOLD_PRINCIPAL'),
	SRC_IN.REMAINING_ZERO_INTEREST_CYCLES.alias('REMAINING_ZERO_INTEREST_CYCLES'),
	SRC_IN.REO_PROPERTY_NUMBER.alias('REO_PROPERTY_NUMBER'),
	SRC_IN.REO_STATUS_DATE.alias('REO_STATUS_DATE'),
	SRC_IN.REPERFORMANCE_LOAN_DUE_DATE.alias('REPERFORMANCE_LOAN_DUE_DATE'),
	SRC_IN.RTC_ASSET_TYPE.alias('RTC_ASSET_TYPE'),
	SRC_IN.RTC_MONTHLY_COLATERAL_FEE.alias('RTC_MONTHLY_COLATERAL_FEE'),
	SRC_IN.RTC_MONTHLY_DEL_FEE.alias('RTC_MONTHLY_DEL_FEE'),
	SRC_IN.RTC_MONTHLY_FEE.alias('RTC_MONTHLY_FEE'),
	SRC_IN.RTC_MONTHLY_PAYOFF_FEE.alias('RTC_MONTHLY_PAYOFF_FEE'),
	SRC_IN.SALE_CURRENT_SERVICE_FEE_RATE.alias('SALE_CURRENT_SERVICE_FEE_RATE'),
	SRC_IN.SALE_MONTHLY_COLATERAL_FEE.alias('SALE_MONTHLY_COLATERAL_FEE'),
	SRC_IN.SALE_MONTHLY_DEL_FEE.alias('SALE_MONTHLY_DEL_FEE'),
	SRC_IN.SALE_MONTHLY_FEE.alias('SALE_MONTHLY_FEE'),
	SRC_IN.SALE_MONTHLY_PAYOFF_FEE.alias('SALE_MONTHLY_PAYOFF_FEE'),
	SRC_IN.SALE_MONTHLY_SPECIAL_FEE.alias('SALE_MONTHLY_SPECIAL_FEE'),
	SRC_IN.SALE_NET_INT_ADV.alias('SALE_NET_INT_ADV'),
	SRC_IN.SALE_NET_YIELD_ADDL_YIELD.alias('SALE_NET_YIELD_ADDL_YIELD'),
	SRC_IN.SALE_NET_YIELD_FIRST_MAX_DECR.alias('SALE_NET_YIELD_FIRST_MAX_DECR'),
	SRC_IN.SALE_NET_YIELD_FIRST_MAX_INCR.alias('SALE_NET_YIELD_FIRST_MAX_INCR'),
	SRC_IN.SALE_NET_YIELD_LIFE_CAP.alias('SALE_NET_YIELD_LIFE_CAP'),
	SRC_IN.SALE_NET_YIELD_LIFE_FLOOR.alias('SALE_NET_YIELD_LIFE_FLOOR'),
	SRC_IN.SALE_NET_YIELD_MARGIN.alias('SALE_NET_YIELD_MARGIN'),
	SRC_IN.SALE_NET_YIELD_MAX_RATE_DECR.alias('SALE_NET_YIELD_MAX_RATE_DECR'),
	SRC_IN.SALE_NET_YIELD_MAX_RATE_INCR.alias('SALE_NET_YIELD_MAX_RATE_INCR'),
	SRC_IN.SALE_NET_YIELD_MAX_SERV_FEE.alias('SALE_NET_YIELD_MAX_SERV_FEE'),
	SRC_IN.SALE_NET_YIELD_MIN_SERV_FEE.alias('SALE_NET_YIELD_MIN_SERV_FEE'),
	SRC_IN.SALE_NET_YIELD_ROUNDING_CODE.alias('SALE_NET_YIELD_ROUNDING_CODE'),
	SRC_IN.SALE_NET_YIELD_ROUNDING_FACTOR.alias('SALE_NET_YIELD_ROUNDING_FACTOR'),
	SRC_IN.SALE_NUMERIC.alias('SALE_NUMERIC'),
	SRC_IN.SALE_PRINCIPAL_ADV.alias('SALE_PRINCIPAL_ADV'),
	SRC_IN.SALE_REPORTING_STATUS.alias('SALE_REPORTING_STATUS'),
	SRC_IN.SALE_SCHEDULED_NOTE_RATE.alias('SALE_SCHEDULED_NOTE_RATE'),
	SRC_IN.SALE_SCHEDULED_PART_PRINCIPAL.alias('SALE_SCHEDULED_PART_PRINCIPAL'),
	SRC_IN.SALE_SCHEDULED_PAYMENT.alias('SALE_SCHEDULED_PAYMENT'),
	SRC_IN.SALE_SCHEDULED_PRINCIPAL.alias('SALE_SCHEDULED_PRINCIPAL'),
	SRC_IN.SALE_SCHEDULED_SERVICE_FEE.alias('SALE_SCHEDULED_SERVICE_FEE'),
	SRC_IN.SALE_SERV_FEE_CALC_CODE.alias('SALE_SERV_FEE_CALC_CODE'),
	SRC_IN.SALE_SERV_FEE_PRIORITY_CODE.alias('SALE_SERV_FEE_PRIORITY_CODE'),
	SRC_IN.SALE_SOLD_PRINCIPAL.alias('SALE_SOLD_PRINCIPAL'),
	SRC_IN.SCHEDULED_BALANCE.alias('SCHEDULED_BALANCE'),
	SRC_IN.SCHEDULED_FORECLOSURE_DATE.alias('SCHEDULED_FORECLOSURE_DATE'),
	SRC_IN.SERVICER_CATEGORY.alias('SERVICER_CATEGORY'),
	SRC_IN.SERVICER_CUSTNO.alias('SERVICER_CUSTNO'),
	SRC_IN.SERVICER_LOAN_NUMERIC.alias('SERVICER_LOAN_NUMERIC'),
	SRC_IN.SERVICER_STOP_ADVANCING_CODE.alias('SERVICER_STOP_ADVANCING_CODE'),
	SRC_IN.SERVICE_FEE_ACCRUAL_CODE.alias('SERVICE_FEE_ACCRUAL_CODE'),
	SRC_IN.SERV_INT_ADV_LAST_INV_CUTOFF.alias('SERV_INT_ADV_LAST_INV_CUTOFF'),
	SRC_IN.SERV_REL_DUE_DATE.alias('SERV_REL_DUE_DATE'),
	SRC_IN.SERV_REL_PART_NOTE_INT_ADV.alias('SERV_REL_PART_NOTE_INT_ADV'),
	SRC_IN.SERV_REL_PART_PRIN_ADV.alias('SERV_REL_PART_PRIN_ADV'),
	SRC_IN.SERV_REL_PART_SERV_FEE_ADV.alias('SERV_REL_PART_SERV_FEE_ADV'),
	SRC_IN.SERV_REL_PRINCIPAL_BALANCE.alias('SERV_REL_PRINCIPAL_BALANCE'),
	SRC_IN.SERV_PRIN_ADV_LAST_INV_CUTOFF.alias('SERV_PRIN_ADV_LAST_INV_CUTOFF'),
	SRC_IN.SHORT_PMT_INTEREST_APPLIED.alias('SHORT_PMT_INTEREST_APPLIED'),
	SRC_IN.SHORT_PMT_PRINCIPAL_APPLIED.alias('SHORT_PMT_PRINCIPAL_APPLIED'),
	SRC_IN.SINGLE_DEBIT_INTEREST_FORECAST.alias('SINGLE_DEBIT_INTEREST_FORECAST'),
	SRC_IN.SINGLE_DEBIT_PART_PMT_CONSTANT.alias('SINGLE_DEBIT_PART_PMT_CONSTANT'),
	SRC_IN.SINGLE_DEBIT_PART_PRINCIPAL.alias('SINGLE_DEBIT_PART_PRINCIPAL'),
	SRC_IN.SINGLE_DEBIT_PRINCIPAL.alias('SINGLE_DEBIT_PRINCIPAL'),
	SRC_IN.SINGLE_DEBIT_PRIN_FORECAST.alias('SINGLE_DEBIT_PRIN_FORECAST'),
	SRC_IN.STATE_CODE.alias('STATE_CODE'),
	SRC_IN.STOP_ADVANCING_CUTOFF_DATE.alias('STOP_ADVANCING_CUTOFF_DATE'),
	SRC_IN.SUB_OF_TRUSTEE_RECEIPT_DATE.alias('SUB_OF_TRUSTEE_RECEIPT_DATE'),
	SRC_IN.SUB_OF_TRUSTEE_RETURN_DATE.alias('SUB_OF_TRUSTEE_RETURN_DATE'),
	SRC_IN.TITLE_POLICY_HOLDER_CODE.alias('TITLE_POLICY_HOLDER_CODE'),
	SRC_IN.TRAN_AGENCY_CURT_AMT.alias('TRAN_AGENCY_CURT_AMT'),
	SRC_IN.TRAN_AGENCY_CURT_AMT_DATE.alias('TRAN_AGENCY_CURT_AMT_DATE'),
	SRC_IN.TRAN_ANCILLARY_FEES_INDICATOR.alias('TRAN_ANCILLARY_FEES_INDICATOR'),
	SRC_IN.TRAN_CAPITALIZED_INT_DUE_DATE.alias('TRAN_CAPITALIZED_INT_DUE_DATE'),
	SRC_IN.TRAN_CAPITALIZED_INTEREST.alias('TRAN_CAPITALIZED_INTEREST'),
	SRC_IN.TRAN_CURTAILMENT_AMT_1.alias('TRAN_CURTAILMENT_AMT_1'),
	SRC_IN.TRAN_CURTAILMENT_AMT_1_DATE.alias('TRAN_CURTAILMENT_AMT_1_DATE'),
	SRC_IN.TRAN_CURTAILMENT_AMT_2.alias('TRAN_CURTAILMENT_AMT_2'),
	SRC_IN.TRAN_CURTAILMENT_AMT_2_DATE.alias('TRAN_CURTAILMENT_AMT_2_DATE'),
	SRC_IN.TRAN_DEFERRED_INTEREST_AMT.alias('TRAN_DEFERRED_INTEREST_AMT'),
	SRC_IN.TRAN_DEFERRED_PRIN_DUE_DATE_1.alias('TRAN_DEFERRED_PRIN_DUE_DATE_1'),
	SRC_IN.TRAN_DEFERRED_PRIN_DUE_DATE_2.alias('TRAN_DEFERRED_PRIN_DUE_DATE_2'),
	SRC_IN.TRAN_DEFERRED_PRINCIPAL_AMT_1.alias('TRAN_DEFERRED_PRINCIPAL_AMT_1'),
	SRC_IN.TRAN_DEFERRED_PRINCIPAL_AMT_2.alias('TRAN_DEFERRED_PRINCIPAL_AMT_2'),
	SRC_IN.TRAN_DUE_DATE.alias('TRAN_DUE_DATE'),
	SRC_IN.TRAN_MOD_INDICATOR.alias('TRAN_MOD_INDICATOR'),
	SRC_IN.TAPE_HISTORY_TRAN_TIMESTAMP.alias('TAPE_HISTORY_TRAN_TIMESTAMP'),
	SRC_IN.TRAN_INT_CHARGED_ON_ARREARS.alias('TRAN_INT_CHARGED_ON_ARREARS'),
	SRC_IN.TRAN_INT_PAID_ON_ARREARS.alias('TRAN_INT_PAID_ON_ARREARS'),
	SRC_IN.TRAN_MODIFIED_LOAN_PRINCIPAL.alias('TRAN_MODIFIED_LOAN_PRINCIPAL'),
	SRC_IN.TRAN_PAYOFF.alias('TRAN_PAYOFF'),
	SRC_IN.TRAN_PAYOFF_REPORT_RECEIVED.alias('TRAN_PAYOFF_REPORT_RECEIVED'),
	SRC_IN.TRAN_PREPAID_AMOUNT.alias('TRAN_PREPAID_AMOUNT'),
	SRC_IN.TRAN_SHORT_PAYMENT_APPLIED.alias('TRAN_SHORT_PAYMENT_APPLIED'),
	SRC_IN.TRAN_STATUS.alias('TRAN_STATUS'),
	SRC_IN.TRAN_STOP_ADVANCING_CODE.alias('TRAN_STOP_ADVANCING_CODE'),
	SRC_IN.UK_ACCRUED_INTEREST.alias('UK_ACCRUED_INTEREST'),
	SRC_IN.UK_ACCRUED_PRINCIPAL.alias('UK_ACCRUED_PRINCIPAL'),
	SRC_IN.UK_AMORTIZATION_METHOD.alias('UK_AMORTIZATION_METHOD'),
	SRC_IN.UNPAID_CHARGED_INTEREST.alias('UNPAID_CHARGED_INTEREST'),
	SRC_IN.UNREMITTED_STRIP_NOT_ADVANCED.alias('UNREMITTED_STRIP_NOT_ADVANCED'),
	SRC_IN.UNSCHEDULED_AMORTIZATION.alias('UNSCHEDULED_AMORTIZATION'),
	SRC_IN.YTD_INTEREST_PAID.alias('YTD_INTEREST_PAID'),
	SRC_IN.YTD_SERVICE_FEE_PAID.alias('YTD_SERVICE_FEE_PAID'),
	SRC_IN.ZIP_CODE.alias('ZIP_CODE'),
	SRC_IN.TREAT_DEF_AS_LOSS_INV_CODE.alias('TREAT_DEF_AS_LOSS_INV_CODE'),
	SRC_IN.TREAT_DEF_AS_LOSS_SERV_CODE.alias('TREAT_DEF_AS_LOSS_SERV_CODE'),
	SRC_IN.SERVICER_INVESTOR_CATEGORY.alias('SERVICER_INVESTOR_CATEGORY'),
	SRC_IN.SERVICER_INVESTOR_CODE.alias('SERVICER_INVESTOR_CODE'),
	SRC_IN.DEF_PRIN_COMPONENT_1.alias('DEF_PRIN_COMPONENT_1'),
	SRC_IN.DEF_PRIN_COMPONENT_2.alias('DEF_PRIN_COMPONENT_2'),
	SRC_IN.TRAN_CAPITALIZED_OTHER.alias('TRAN_CAPITALIZED_OTHER'),
	SRC_IN.TRAN_DEF_PRIN_COMP_1_AMT.alias('TRAN_DEF_PRIN_COMP_1_AMT'),
	SRC_IN.TRAN_DEF_PRIN_COMP_1_DUE_DATE.alias('TRAN_DEF_PRIN_COMP_1_DUE_DATE'),
	SRC_IN.TRAN_DEF_PRIN_COMP_2_AMT.alias('TRAN_DEF_PRIN_COMP_2_AMT'),
	SRC_IN.TRAN_DEF_PRIN_COMP_2_DUE_DATE.alias('TRAN_DEF_PRIN_COMP_2_DUE_DATE'),
	SRC_IN.TRAN_MOD_DEF_AS_LOSS_S_CD.alias('TRAN_MOD_DEF_AS_LOSS_S_CD'),
	SRC_IN.TRAN_MOD_DEF_AS_LOSS_S_CD_1.alias('TRAN_MOD_DEF_AS_LOSS_S_CD_1'),
	SRC_IN.TRAN_MOD_DEF_AS_LOSS_S_CD_2.alias('TRAN_MOD_DEF_AS_LOSS_S_CD_2'),
	SRC_IN.TREAT_DEF_AS_LOSS_INV_CODE_1.alias('TREAT_DEF_AS_LOSS_INV_CODE_1'),
	SRC_IN.TREAT_DEF_AS_LOSS_INV_CODE_2.alias('TREAT_DEF_AS_LOSS_INV_CODE_2'),
	SRC_IN.TREAT_DEF_AS_LOSS_SERV_CODE_1.alias('TREAT_DEF_AS_LOSS_SERV_CODE_1'),
	SRC_IN.TREAT_DEF_AS_LOSS_SERV_CODE_2.alias('TREAT_DEF_AS_LOSS_SERV_CODE_2'),
	SRC_IN.INV_STOP_ADVANCING_CUTOFF_DATE.alias('INV_STOP_ADVANCING_CUTOFF_DATE'),
	SRC_IN.SERVICE_FEE_DEAL_NUMBER.alias('SERVICE_FEE_DEAL_NUMBER'),
	SRC_IN.FHA_DEFAULT_DEBENTURE_DATE.alias('FHA_DEFAULT_DEBENTURE_DATE'),
	SRC_IN.NOTE_RATE_TOLERANCE.alias('NOTE_RATE_TOLERANCE'),
	SRC_IN.PAYMENT_TOLERANCE_AMOUNT.alias('PAYMENT_TOLERANCE_AMOUNT'),
	SRC_IN.FACILITY_CODE.alias('FACILITY_CODE'),
	SRC_IN.INPROCESS_RECLASS.alias('INPROCESS_RECLASS'),
	SRC_IN.PAYMENT_TOLERANCE_PERCENT.alias('PAYMENT_TOLERANCE_PERCENT'),
	SRC_IN.CURRENT_MASTER_SERVICER_ADV.alias('CURRENT_MASTER_SERVICER_ADV'),
	SRC_IN.ORIGINAL_MASTER_SERVICER_ADV.alias('ORIGINAL_MASTER_SERVICER_ADV'),
	SRC_IN.PMT_FIRST_FULL_ADJUSTMENT_DATE.alias('PMT_FIRST_FULL_ADJUSTMENT_DATE'),
	SRC_IN.REPAIR_AND_REPLACEMENT_BALANCE.alias('REPAIR_AND_REPLACEMENT_BALANCE'),
	SRC_IN.TAX_AND_INSURANCE_BALANCE.alias('TAX_AND_INSURANCE_BALANCE'),
	SRC_IN.INCOME_RECOGNITION_METHOD.alias('INCOME_RECOGNITION_METHOD'),
	SRC_IN.REPAIR_FLAG.alias('REPAIR_FLAG'),
	SEQ_IN_joined.MFPB.alias('MFPB'),
	SEQ_IN_joined.MSPB.alias('MSPB'),
	SEQ_IN_joined.MFPBPlusMSPB.alias('MFPBPlusMSPB'),
	SBO_Sale_Lkp.GLACT_PRINCIPAL.alias('SBO_SALE_GLACT_PRINCIPAL'),
	SBO_Sale_Lkp.USER_1.alias('SBO_SALE_USER_1'),
	SBO_Sale_Lkp.USER_2.alias('SBO_SALE_USER_2'),
	SBO_Sale_Lkp.USER_3.alias('SBO_SALE_USER_3'),
	SBO_Sale_Lkp.USER_4.alias('SBO_SALE_USER_4'),
	SBO_Sale_Lkp.USER_5.alias('SBO_SALE_USER_5'),
	SBO_ZRF_Lkp.ANNUAL_INT_RATE.alias('SBO_ZRF_ANNUAL_INT_RATE'),
	SBO_ZRF_Lkp.ARM_IR_BASE_RATE_1.alias('SBO_ZRF_ARM_IR_BASE_RATE_1'),
	SBO_ZRF_Lkp.BILLING_ADDRESS_LINE_2.alias('SBO_ZRF_BILLING_ADDRESS_LINE_2'),
	SBO_ZRF_Lkp.BILLING_ADDRESS_LINE_3.alias('SBO_ZRF_BILLING_ADDRESS_LINE_3'),
	SBO_ZRF_Lkp.BILLING_ADDRESS_LINE_4.alias('SBO_ZRF_BILLING_ADDRESS_LINE_4'),
	SBO_ZRF_Lkp.BILLING_BORROWER_NAME.alias('SBO_ZRF_BILLING_BORROWER_NAME'),
	SBO_ZRF_Lkp.BILLING_CITY_NAME.alias('SBO_ZRF_BILLING_CITY_NAME'),
	SBO_ZRF_Lkp.BILLING_COBORROWER_NAME.alias('SBO_ZRF_BILLING_COBORROWER_NAME'),
	SBO_ZRF_Lkp.BILLING_STATE.alias('SBO_ZRF_BILLING_STATE'),
	SBO_ZRF_Lkp.BILLING_ZIP_CODE.alias('SBO_ZRF_BILLING_ZIP_CODE'),
	SBO_ZRF_Lkp.CHARGED_OFF_GROSS_LTD_NBA.alias('SBO_ZRF_CHARGED_OFF_GROSS_LTD_NBA'),
	SBO_ZRF_Lkp.COLLATERAL_CODE.alias('SBO_ZRF_COLLATERAL_CODE'),
	SBO_ZRF_Lkp.FLOOD_INS_CODE.alias('SBO_ZRF_FLOOD_INS_CODE'),
	SBO_ZRF_Lkp.FORECLOSURE_STOP_CODE.alias('SBO_ZRF_FORECLOSURE_STOP_CODE'),
	SBO_ZRF_Lkp.DIA_PARTICIPANT_CODE.alias('SBO_ZRF_DIA_PARTICIPANT_CODE'),
	SBO_ZRF_Lkp.EMPLOYEE_CODE.alias('SBO_ZRF_EMPLOYEE_CODE'),
	SBO_ZRF_Lkp.LIEN_AMOUNT.alias('SBO_ZRF_LIEN_AMOUNT'),
	SBO_ZRF_Lkp.MORTGAGE_INSURANCE_PAYEE.alias('SBO_ZRF_MORTGAGE_INSURANCE_PAYEE'),
	SBO_ZRF_Lkp.MORTGR_SSN_OR_TIN_INDICATOR.alias('SBO_ZRF_MORTGR_SSN_OR_TIN_INDICATOR'),
	SBO_ZRF_Lkp.PAYMENT_IN_FULL_STOP_CODE.alias('SBO_ZRF_PAYMENT_IN_FULL_STOP_CODE'),
	SBO_ZRF_Lkp.PRIMARY_OFFICER_ID.alias('SBO_ZRF_PRIMARY_OFFICER_ID'),
	SBO_ZRF_Lkp.PRINCIPAL_BALANCE.alias('SBO_ZRF_PRINCIPAL_BALANCE'),
	SBO_ZRF_Lkp.DRAFT_ACCOUNT_NUMBER.alias('SBO_ZRF_DRAFT_ACCOUNT_NUMBER'),
	SBO_ZRF_Lkp.DRAFTING_INDICATOR.alias('SBO_ZRF_DRAFTING_INDICATOR'),
	SBO_ZRF_Lkp.SECOND_ANNUAL_INTEREST_RATE.alias('SBO_ZRF_SECOND_ANNUAL_INTEREST_RATE'),
	SBO_ZRF_Lkp.SECOND_PRINCIPAL_BALANCE.alias('SBO_ZRF_SECOND_PRINCIPAL_BALANCE'),
	SBO_ZRF_Lkp.SECOND_TELEPHONE_NUMBER.alias('SBO_ZRF_SECOND_TELEPHONE_NUMBER'),
	SBO_ZRF_Lkp.TELEPHONE_CODE.alias('SBO_ZRF_TELEPHONE_CODE'),
	SBO_ZRF_Lkp.TELEPHONE_NUMBER.alias('SBO_ZRF_TELEPHONE_NUMBER'),
	SBO_ZRF_Lkp.SECONDARY_OFFICER_ID.alias('SBO_ZRF_SECONDARY_OFFICER_ID'),
	SBO_ZRF_Lkp.YTD_INTEREST_AMOUNT.alias('SBO_ZRF_YTD_INTEREST_AMOUNT'),
	SBO_LAF_Lkp.ARM_PLAN_CODE.alias('SBO_LAF_ARM_PLAN_CODE'),
	SBO_LAF_Lkp.BORROWER_BIRTHDATE.alias('SBO_LAF_BORROWER_BIRTHDATE'),
	SBO_LAF_Lkp.BORROWER_CITIZEN_CODE.alias('SBO_LAF_BORROWER_CITIZEN_CODE'),
	SBO_LAF_Lkp.BORROWER_DEATHDATE.alias('SBO_LAF_BORROWER_DEATHDATE'),
	SBO_LAF_Lkp.BORROWER_NAME_SUFFIX.alias('SBO_LAF_BORROWER_NAME_SUFFIX'),
	SBO_LAF_Lkp.BORROWER_MONTHLY_INCOME.alias('SBO_LAF_BORROWER_MONTHLY_INCOME'),
	SBO_LAF_Lkp.CLOSING_DATE.alias('SBO_LAF_CLOSING_DATE'),
	SBO_LAF_Lkp.DISCOUNT_BALANCE_1.alias('SBO_LAF_DISCOUNT_BALANCE_1'),
	SBO_LAF_Lkp.DISCOUNT_BALANCE_2.alias('SBO_LAF_DISCOUNT_BALANCE_2'),
	SBO_LAF_Lkp.DISCOUNT_BALANCE_3.alias('SBO_LAF_DISCOUNT_BALANCE_3'),
	SBO_LAF_Lkp.DISCOUNT_BALANCE_6.alias('SBO_LAF_DISCOUNT_BALANCE_6'),
	SBO_LAF_Lkp.DISCOUNT_BALANCE_7.alias('SBO_LAF_DISCOUNT_BALANCE_7'),
	SBO_LAF_Lkp.DISCOUNT_BALANCE_8.alias('SBO_LAF_DISCOUNT_BALANCE_8'),
	SBO_LAF_Lkp.DISCOUNT_BALANCE_9.alias('SBO_LAF_DISCOUNT_BALANCE_9'),
	SBO_LAF_Lkp.FICO_SCORE_1.alias('SBO_LAF_FICO_SCORE_1'),
	SBO_LAF_Lkp.DEBT_RATIO.alias('SBO_LAF_DEBT_RATIO'),
	SBO_LAF_Lkp.ORIGINAL_LTV.alias('SBO_LAF_ORIGINAL_LTV'),
	SBO_LAF_Lkp.PMI_INITIAL_PREMIUM_RATE.alias('SBO_LAF_PMI_INITIAL_PREMIUM_RATE'),
	SBO_LAF_Lkp.USER_9.alias('SBO_LAF_USER_9'),
	SBO_Indx_Lkp.CROSS_REFERENCE_TO_LEGACY.alias('SBO_INDX_CROSS_REFERENCE_TO_LEGACY'),
	SBO_Delq_Lkp.CUTOFF_DATE_0.alias('SBO_DELQ_CUTOFF_DATE_0'),
	SBO_Control_Lkp.INVESTOR_REPORTING_CUTOFF_DATE.alias('SBO_CONTROL_INVESTOR_REPORTING_CUTOFF_DATE'),
	SBO_DA_LKP.EFFECTIVE_DATE.alias('SBO_DA_EFFECTIVE_DATE'),
	SBO_DA_LKP.LOAN_PERFORMING_INDICATOR.alias('SBO_DA_LOAN_PERFORMING_INDICATOR'),
	SBO_BkrpTrac_LKP.CHAPTER.alias('SBO_BKRPT_TRCNG_CHAPTER'),
	SBO_BkrpTrac_LKP.FILING_DATE.alias('SBO_BKRPT_TRCNG_FILING_DATE'),
	SBO_Purchase_LKP.PURCHASE_NUMBER.alias('SBO_PURCH_PURCHASE_NUMBER'),
	SBO_Sale_Lkp.USER_8.alias('SBO_SALE_USER_8'),
	SBO_ZRF_Lkp.ACCRUED_LATE_CHARGE_AMOUNT.alias('ZRF_ACCRUED_LATE_CHARGE_AMOUNT'),
	SBO_LAF_Lkp.TOTAL_MONTHLY_PAYMENT.alias('LAF_TOTAL_MONTHLY_PAYMENT'),
	SBO_LAF_Lkp.USER_8.alias('LAF_USER_8'),
	SBO_LAF_Lkp.UNDERWRITER_NAME.alias('LAF_UNDERWRITER_NAME'),
	(trim(SRC_IN.LOAN_NUMERIC)).alias('LOAN_NO'),
	SBO_Sale_Lkp.OWNERSHIP_CODE.alias('OWNERSHIP_CODE'),
	SBO_ZRF_Lkp.MOD_PROPERTY_VALUE_AMOUNT.alias('MOD_PROPERTY_VALUE_AMOUNT'),
	SBO_ZRF_Lkp.MOD_PROPERTY_VALUE_DATE.alias('MOD_PROPERTY_VALUE_DATE'),
	SBO_Sale_Lkp.SALE_NAME.alias('SALE_NAME'),
	SBO_LAF_Lkp.BUY_DOWN_FLAG.alias('BUY_DOWN_FLAG'),
	SBO_LAF_Lkp.DOCUMENTATION_TYPE_CODE.alias('DOCUMENTATION_TYPE_CODE'),
	SBO_LAF_Lkp.LOAN_ORIGINATION_SOURCE.alias('LOAN_ORIGINATION_SOURCE'),
	SBO_LAF_Lkp.COMBINED_ORIGINAL_LTV_RATIO.alias('COMBINED_ORIGINAL_LTV_RATIO'),
	SBO_LAF_Lkp.RECOURSE_EXPIRATION_DATE.alias('RECOURSE_EXPIRATION_DATE'),
	SBO_LAF_Lkp.RECOURSE_TYPE.alias('RECOURSE_TYPE'),
	SBO_LAF_Lkp.LOAN_TO_VALUE_RATIO.alias('LOAN_TO_VALUE_RATIO'),
	SBO_ZRF_Lkp.FC_SALE_DATE.alias('FC_SALE_DATE'),
	SBO_ZRF_Lkp.FC_SUSPEND_DATE.alias('FC_SUSPEND_DATE'),
	SBO_ZRF_Lkp.FP_STATUS_CODE_DESCRIPTION.alias('FP_STATUS_CODE_DESCRIPTION'),
	SBO_ZRF_Lkp.MOD_POST_AMORTIZATION_TERM.alias('MOD_POST_AMORTIZATION_TERM'),
	SBO_ZRF_Lkp.MOD_INTEREST_RATE_STEP_FLAG.alias('MOD_INTEREST_RATE_STEP_FLAG'),
	SBO_ZRF_Lkp.MOD_PRE_AMORTIZATION_TERM.alias('MOD_PRE_AMORTIZATION_TERM'),
	SBO_ZRF_Lkp.MOD_DEFERRED_PRINCIPAL_AMOUNT.alias('MOD_DEFERRED_PRINCIPAL_AMOUNT'),
	SBO_ZRF_Lkp.MOD_TOTAL_CAPITALIZED_AMOUNT.alias('MOD_TOTAL_CAPITALIZED_AMOUNT'),
	SBO_ZRF_Lkp.LOSS_MIT_INDICATOR_DESC.alias('LOSS_MIT_INDICATOR_DESC'),
	SBO_ZRF_Lkp.LOSS_MIT_STATUS_CODE_DESC.alias('LOSS_MIT_STATUS_CODE_DESC'),
	SBO_ZRF_Lkp.MOD_INFO_AFTER_INTEREST_RATE.alias('MOD_INFO_AFTER_INTEREST_RATE'),
	SBO_ZRF_Lkp.MOD_POST_LTV_RATIO.alias('MOD_POST_LTV_RATIO'),
	SBO_ZRF_Lkp.MOD_INFO_BEFORE_INTEREST_RATE.alias('MOD_INFO_BEFORE_INTEREST_RATE'),
	SBO_ZRF_Lkp.MOD_POST_REMAINING_TERM.alias('MOD_POST_REMAINING_TERM'),
	SBO_ZRF_Lkp.MOD_POST_MTHLY_ESCR_PMT_AMOUNT.alias('MOD_POST_MTHLY_ESCR_PMT_AMOUNT'),
	SBO_ZRF_Lkp.MOD_PRE_MTHLY_ESCR_PMT_AMOUNT.alias('MOD_PRE_MTHLY_ESCR_PMT_AMOUNT'),
	SBO_ZRF_Lkp.REPAY_PLAN_CODE.alias('REPAY_PLAN_CODE'),
	SBO_ZRF_Lkp.NON_REC_CORP_ADVANCE_BALANCE.alias('NON_REC_CORP_ADVANCE_BALANCE'),
	SBO_ZRF_Lkp.THIRD_PARTY_RECOVERABLE_CA_BAL.alias('THIRD_PARTY_RECOVERABLE_CA_BAL'),
	SBO_ZRF_Lkp.MOD_INFO_BEFORE_PI_PMT_AMOUNT.alias('MOD_INFO_BEFORE_PI_PMT_AMOUNT'),
	SBO_ZRF_Lkp.MOD_INFO_AFTER_PI_PMT_AMOUNT.alias('MOD_INFO_AFTER_PI_PMT_AMOUNT'),
	SBO_ZRF_Lkp.MOD_PGM_CAMPAIGN_TYPE_DESC.alias('MOD_PGM_CAMPAIGN_TYPE_DESC'),
	SBO_ZRF_Lkp.LOAN_MODIFICATION_DATE.alias('LOAN_MODIFICATION_DATE'),
	SBO_ZRF_Lkp.FC_START_DATE.alias('FC_START_DATE'),
	SBO_ZRF_Lkp.MOD_PRE_REMAINING_TERM.alias('MOD_PRE_REMAINING_TERM'),
	SBO_ZRF_Lkp.MOD_TOTAL_NUMBER_OF_LOAN_MODS.alias('MOD_TOTAL_NUMBER_OF_LOAN_MODS'),
	SBO_Sale_Lkp.GLACT_DISCOUNT_1.alias('GLACT_DISCOUNT_1'),
	SBO_Sale_Lkp.GLACT_DISCOUNT_2.alias('GLACT_DISCOUNT_2'),
	SBO_ZRF_Lkp.PB_NEGATIVE_AMORT_PCT.alias('PB_NEGATIVE_AMORT_PCT'),
	SBO_ZRF_Lkp.CURRENT_APPRAISAL_DATE.alias('CURRENT_APPRAISAL_DATE'),
	SBO_ZRF_Lkp.CURRENT_PROPERTY_VALUE.alias('CURRENT_PROPERTY_VALUE'),
	SBO_Sale_Lkp.USER_6.alias('USER_6')
)